### ISSUE TITLE
[ WARN:0] global /io/opencv/modules/dnn/src/dnn.cpp (1363) setUpNet DNN module was not built with CUDA backend; switching to CPU

### ISSUE THREAD

**Issue by zongoalbert** [Cuda-Chen/opencv-dnn-cuda-test#1]
i found this issue need ure help

**Comment by zongoalbert** [comment]
i used the code python main.py

**Comment by Cuda-Chen** [comment]
It seems like you don’t build with CUDA support.
Can you give me your build configurations (OpenCV version, CMake build settings,etc.)?

**Comment by zongoalbert** [comment]
Hello @Cuda-Chen  , thank you so mluch for your answer . this is my build configurations Opencv : 
![image](https://user-images.githubusercontent.com/55978810/86115084-570bc680-bac3-11ea-9d3d-f1b7b964d104.png)


and i did `Cmake`  like this command lines : 


``$ cmake -D CMAKE_BUILD_TYPE=RELEASE \`

	-D CMAKE_INSTALL_PREFIX=/usr/local \

	-D INSTALL_PYTHON_EXAMPLES=ON \

	-D INSTALL_C_EXAMPLES=OFF \

	-D OPENCV_ENABLE_NONFREE=ON \

	-D WITH_CUDA=ON \

	-D WITH_CUDNN=ON \

	-D OPENCV_DNN_CUDA=ON \

	-D ENABLE_FAST_MATH=1 \

	-D CUDA_FAST_MATH=1 \

	-D CUDA_ARCH_BIN=7.0 \

	-D WITH_CUBLAS=1 \

	-D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib/modules \

	-D HAVE_opencv_python3=ON \


	-D BUILD_EXAMPLES=ON ..`

**Comment by zongoalbert** [comment]
please Sir , Any help you could  provide would be greatly appreciated

**Comment by Cuda-Chen** [comment]
Hi @zongoalbert ,
I guess there are some wrong settings.
So can you paste your GPU model and what kind of virtualenv you are using?

Hint: you can get your GPU model use `nvidia-smi`.

**Comment by zongoalbert** [comment]
i dont use virtualenv , i just use env anaconda and install opencv with this make  : 
this is the result of  `nvidia-smi`
![image](https://user-images.githubusercontent.com/55978810/86146663-6c4b1a00-baf0-11ea-9be6-945d8388b50b.png)

**Comment by Cuda-Chen** [comment]
After I checked this [site](https://developer.nvidia.com/cuda-gpus),
you should set `CUDA_ARCH_BIN` to `7.5` rather than `7.0`.

After setting, recompile OpenCV then install.
Then report your result here.

**Comment by zongoalbert** [comment]
thank you @Cuda-Chen ,i will try reinstall it Now

**Comment by zongoalbert** [comment]
unfortunately i found the same issue @Cuda-Chen  :/

**Comment by Cuda-Chen** [comment]
I guess your conda environment can't find the built shared library, isn't it?

**Comment by zongoalbert** [comment]
how can be make sure that conda env find or not the build shared library?

**Comment by Cuda-Chen** [comment]
Usually I use/create a conda env **without** installing OpenCV pip package.
Then type`python -c "import cv2; print(cv2.__version__);"` in terminal.
If it complains it can't find `cv2`, that means either you don't install OpenCV pip package or link to OpenCV shared library.
Since we don't install OpenCV pip package, that means it doesn't find OpenCV shared library.

I think you can try to install `virtualenv` package first and report the result here.
Then we can think how to add our built shared library to conda env together :)

**Comment by zongoalbert** [comment]
WOOOW ,, You are amazing , its work perfectly with `virtualenv`   the problem is about **Symbolic Link**
i used this command lines after create virtualenv: 
`$ ls -l /usr/local/lib/python3.6/site-packages/cv2/python-3.6
total 7168
-rw-r--r-
1 root staff 7339240 Jan 17 18:59 cv2.cpython-36m-x86_64-linux-gnu.so`

then : 
`$ cd ~/.virtualenvs/opencv_cuda/lib/python3.5/site-packages/
$ ln -s /usr/local/lib/python3.6/site-packages/cv2/python-3.6/cv2.cpython-36m-x86_64-linux-gnu.so cv2.so`


after that `python -c "import cv2; print(cv2.__version__);` finaly i can find `cv2`

when i tested your project it's give me this results ^_^
 
`(opencv_cuda) (base) bpros@bpros-HP-ZBook-17-G6:~/Documents/opencv-dnn-cuda-test-master/python_code$ python main.py 
Time per inference: 46.528792 ms
FPS:  21.492068648705985
`
but i have an other issue how can be tested it with conda env ?
thank you so much sir for your help ,

**Comment by Cuda-Chen** [comment]
I haven't tested with conda env.
But I guess you can symlink the built library to the conda env.

**Comment by zongoalbert** [comment]
Hello ,about utilization of  GPU how to improve it : 
like you see  when i tap command line  : `watch nvidia-smi` to wach utilization of GPU: i found that script python  use just 985 MIb of GPU, 
![image](https://user-images.githubusercontent.com/55978810/86245937-26e72500-bba2-11ea-9c5c-a56795fc3f64.png)

how can be improve utilisation of GPU , many thanks .

**Comment by zongoalbert** [comment]
please i know that question its not similar on this issue , should i creat an other issue ?

**Comment by Cuda-Chen** [comment]
> please i know that question its not similar on this issue , should i creat an other issue ?

I think you can create an other issue to talk about this.
